### ISSUE TITLE
publish release to expose latest changes

### ISSUE THREAD

**Issue by thepiwo** [voxpelli/node-pg-pubsub#115]
Hello, thanks for this library, will there be a new release soon, to expose the latest changes? I am facing some issues with typescript ` Cannot extend an interface 'NodeJS.EventEmitter'` which seem to be already fixed on `main` with https://github.com/voxpelli/node-pg-pubsub/commit/136a4005edc50fcffb39fc7c55f604f90ff72e32#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L10

**Comment by voxpelli** [comment]
Sorry, missed this, I'll try to give it a look as soon as possible, maybe later this evening
