### ISSUE TITLE
SQL injection vulnerability

### ISSUE THREAD

**Issue by bsutherland** [voxpelli/node-pg-pubsub#12]
It looks like you're using plain string concatenation to build your queries. How about using the built in parameter substitution of the query method from the pg package?

**Comment by voxpelli** [comment]
Because the calls aren't really queries and thus that escaping can't be used – but the same escaping is still used as of this commit: https://github.com/voxpelli/node-pg-pubsub/commit/82db22a5b6ec27dd95be4e8e0e812de627fd5c9f
