### ISSUE TITLE
Impossible to handle connection errors

### ISSUE THREAD

**Issue by oliversalzburg** [voxpelli/node-pg-pubsub#5]
When the database is not available, pg-pubsub will retry connecting forever without any option for the user to intervene.

What's even worse is another related issue that I can't reproduce while debugging.

When I run pg-pubsub in the debugger, my console output will look like this:

```
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } 'Failed retry attempt for pubsub'
Retry 1: Waiting 77 ms to try pubsub again
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } 'Failed retry attempt for pubsub'
Retry 2: Waiting 758 ms to try pubsub again
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } 'Failed retry attempt for pubsub'
Retry 3: Waiting 1276 ms to try pubsub again
```

In a non-debug run, the behavior is completely different:

```
{ [error: database "x" does not exist] } 'Failed retry attempt for pubsub'
Retry 1: Waiting 677 ms to try pubsub again
{ [error: database "x" does not exist] } 'Failed retry attempt for pubsub'
Retry 1: Waiting 694 ms to try pubsub again
{ [error: database "x" does not exist] } 'Failed retry attempt for pubsub'
Retry 1: Waiting 581 ms to try pubsub again
```

Here, the failure count isn't increased at all, because the handler for `db.on('error')` is triggered, which calls `self.retry.reset();`, leading to an infinite loop.

I'm not sure what the purpose of that error handler is, but it's counter-productive and should be removed IMHO.

Additionally, I would recommend changing the `try` function to check for the failure count like so:

```js
function() {
	var db = new pg.Client( self.conString );
	return new Promise( function( resolve, reject ) {
		db.connect( function( err ) {
			if( err ) {
				if( self.retry.failures > 9 ) {
					self.retry.end();
				}
				reject( err );
			} else {
				resolve( db );
			}
		} );
	} );
}
```

This will ultimately lead to the rejection of the promise returned from calling `retry.try` in pg-pubsub. Which, in turn, allows us to control connecting to postgres and handle connection errors:

```js
pubsub.retry.try()
	.then( function() {
		console.log( "Successfully connected to postgres." );
	} )
	.catch( function( err ) {
		console.error( err );
	} );
```

**Comment by voxpelli** [comment]
Closing this as #6 was closed. Fix was implemented upstream in the `pg` module, which appears to have solved this behavior.
