### ISSUE TITLE
Add Typescript bindings

### ISSUE THREAD

**Issue by IlyaSemenov** [voxpelli/node-pg-pubsub#60]
It would be great if the package included `index.d.ts` for typescript.

**Comment by voxpelli** [comment]
Agree, hopefully this can now be autogenerated: https://voxpelli.com/2019/10/use-type-script-3-7-to-generate/

I just need to find time to do it. Or someone else can try the above and send me a PR.

**Comment by voxpelli** [comment]
Done as of `0.6.0`
