### ISSUE TITLE
SQL Injection on payload

### ISSUE THREAD

**Issue by cristianocca** [voxpelli/node-pg-pubsub#9]
It would be great to have `.replace(/'/g,"''")` added after the JSON.stringify call on the payload so you are protected against injection.
For the channel name, it would be unnecessary since you are not supposed to be using unsafe data as a channel name in the first place, but for the payload as you are allowing objects it's not obvious that it is unsafe right now.

**Comment by voxpelli** [comment]
Thanks for catching this! Released `0.2.3` to fix it.
