### ISSUE TITLE
Doesn't seem to work with Node 14

### ISSUE THREAD

**Issue by bostrom** [voxpelli/node-pg-pubsub#98]
We've been using node-pg-pubsub in our project for quite some time. In an upgrade from Node 10 to Node 14 it stopped working.  More specifically we stopped seeing the `Successful retry attempt for pubsub` notices in the server log and no published messages were picked up. 

Downgrading to Node 12 made it work again, and we left it like that with no further debugging.

Just wanted to let you know that there seems to be some issues with Node 14.

**Comment by voxpelli** [comment]
Huh, weird.

The loss of `Successful retry attempt for pubsub` is expected, the default logger no longer logs anything in production (though you can supply a custom logger which does)

**Comment by voxpelli** [comment]
Which version are you running?

**Comment by bostrom** [comment]
Ah, how stupid of me. We have 0.5.0 so far from the latest version. Sorry about that, will try with the latest and see if that resolves the problem.

**Comment by bostrom** [comment]
Ok, so as far as I can see version 0.6.1 works with Node 14, so closing this. Sorry about the noise.

**Comment by voxpelli** [comment]
No worries @bostrom! Great that it works now 👍
